name: seekcommons
channels:
  - conda-forge
dependencies:
  - python
  - jupyter
  - h5py
  - hdf5
  - hdf5plugin
  - matplotlib
  - notebook
  - pandas
  - pip
  - pip:
    - SPARQLWrapper
    - h5pyd
    - rise